### PR TITLE
Fixing Strips/PixelPhase1/Tracker/Reco conf e visualization

### PR DESCRIPTION
**Pull request by arossi83**
As the title says: updating the configuration files for SiStrips, PixelPhase1, Tracker and Reco in order to be aligned with the last settings from TrackerDPG HDQM instance. Also the visualization configuration has been updated in order to take into account the changes introduced.

Few function on the basic metric added.

### CODE REVIEW

**Comment by arossi83** [comment]
there is a HDQM running instance on lxplus755 where all the changes have been tested. It can be check by typing:
ssh -L 8000:localhost:8000 -L 8080:localhost:5000 <YOUR_USER_NAME>@lxplus755.cern.ch
and then visiting http://localhost:8000

**Comment by jfernan2** [comment]
Thank you for the a priori validation @arossi83 !

**Comment by jfernan2** [comment]
It should be in central HDQM server now

**Comment by arossi83** [comment]
Thanks @jfernan2 for the really quick merge! I wasn't able to finish my email to inform DQM Core of the PR!

**Pull request merged**
